
name: batch252_portal
description: A portal app for Batch252 to share and view study links.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0

flutter:
  uses-material-design: true
